-- Materialized (table-backed) version of view_proteomes_flat_v2 for fast filtering/sorting.
--
-- Why: the original view is built from many correlated subqueries, which is slow at scale.
-- This table can be refreshed after imports, and then queried directly by the API.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS proteomes_flat_mat (
  `hash` VARCHAR(128) NOT NULL,
  `Origin CP` VARCHAR(191),
  `web` TEXT,
  `In NCBI's ref seq` TINYINT(1),
  `Species` VARCHAR(191),
  `taxID` BIGINT,
  `species_taxid` BIGINT,
  `current_scientific_name` VARCHAR(191),
  `common_names` TEXT,
  `group_name` VARCHAR(191),
  `informal_clade` VARCHAR(191),
  `code_vFV` VARCHAR(128),
  `File_name` VARCHAR(191),
  `Filepath_original` TEXT,
  `num_seqs` INT,
  `sum_len` BIGINT,
  `min_len` INT,
  `avg_len` DOUBLE,
  `max_len` INT,
  `File_snip_name` VARCHAR(191),
  `Filepath_snip_processed` TEXT,
  `Filepath_renamed_vFV` TEXT,
  `num_seqs_snip_processed` INT,
  `sum_len_snip_processed` BIGINT,
  `min_len_snip_processed` INT,
  `avg_len_snip_processed` DOUBLE,
  `max_len_snip_processed` INT,
  `post_snip` TINYINT(1),
  `AssemblyID` VARCHAR(191),

  `Complete BUSCO Domain` DOUBLE,
  `Single BUSCO Domain` DOUBLE,
  `Duplicated BUSCO Domain` DOUBLE,
  `Fragmented BUSCO Domain` DOUBLE,
  `Missing BUSCO Domain` DOUBLE,

  `Complete BUSCO Kingdom` DOUBLE,
  `Single BUSCO Kingdom` DOUBLE,
  `Duplicated BUSCO Kingdom` DOUBLE,
  `Fragmented BUSCO Kingdom` DOUBLE,
  `Missing BUSCO Kingdom` DOUBLE,

  `Domain` VARCHAR(191),
  `Realm` VARCHAR(191),
  `Kingdom` VARCHAR(191),
  `Subkingdom` VARCHAR(191),
  `Superphylum` VARCHAR(191),
  `Phylum` VARCHAR(191),
  `Subphylum` VARCHAR(191),
  `Infraphylum` VARCHAR(191),
  `Superclass` VARCHAR(191),
  `Class` VARCHAR(191),
  `Subclass` VARCHAR(191),
  `Infraclass` VARCHAR(191),
  `Cohort` VARCHAR(191),
  `Subcohort` VARCHAR(191),
  `Superorder` VARCHAR(191),
  `Order` VARCHAR(191),
  `Suborder` VARCHAR(191),
  `Infraorder` VARCHAR(191),
  `Parvorder` VARCHAR(191),
  `Superfamily` VARCHAR(191),
  `Family` VARCHAR(191),
  `Subfamily` VARCHAR(191),
  `Tribe` VARCHAR(191),
  `Subtribe` VARCHAR(191),
  `Genus` VARCHAR(191),
  `Subgenus` VARCHAR(191),
  `Section` VARCHAR(191),
  `Subsection` VARCHAR(191),
  `Series` VARCHAR(191),
  `Subseries` VARCHAR(191),
  `Species_group` VARCHAR(191),
  `Species_subgroup` VARCHAR(191),
  `Forma_specialis` VARCHAR(191),
  `Subspecies` VARCHAR(191),
  `VarietasSubvariety` VARCHAR(191),
  `Forma` VARCHAR(191),
  `Serogroup` VARCHAR(191),
  `Serotype` VARCHAR(191),
  `Strain` VARCHAR(191),
  `Isolate` VARCHAR(191),

  PRIMARY KEY (`hash`),
  INDEX idx_species (`Species`),
  INDEX idx_code_vfv (`code_vFV`),
  INDEX idx_taxid (`taxID`),
  INDEX idx_species_taxid (`species_taxid`),
  INDEX idx_phylum (`Phylum`),
  INDEX idx_class (`Class`),
  INDEX idx_order (`Order`),
  INDEX idx_family (`Family`),
  INDEX idx_genus (`Genus`),
  INDEX idx_busco_complete_domain (`Complete BUSCO Domain`),
  INDEX idx_busco_complete_kingdom (`Complete BUSCO Kingdom`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

-- Refresh statement (run via scripts/refresh_flat_table.py, or manually):
--   DELETE FROM proteomes_flat_mat;
--   INSERT INTO proteomes_flat_mat (...) SELECT ...;
